- name: "Accessories"
  description: "Accessories"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - cheese
    - font-manager
    - galculator
    - gpick
    - flameshot
    - liferea
    - mediainfo-gui
    - mediainfo-gui-qt
    - mcomix
    - nomacs
    - pdfarranger
    - plank
    - screenkey
    - variety
- name: "Git"
  description: "Git applications"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - gitahead
    - gitbucket
    - gitg
    - gitfiend
    - github-cli
    - github-desktop
    - gitkraken
- name: "Password Manager"
  description: "Password managers"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - bitwarden
    - enpass-bin
    - keepassxc
    - lastpass
- name: "Privacy"
  description: "Applications that ensure your privacy"
  critical: false
  hidden: false
  selected: false
  expanded: true
  packages:
    - torbrowser-launcher
    - privoxy
- name: "Virtualbox for Linux kernel"
  description: "Installs virtualbox for linux kernel"
  critical: false
  hidden: false
  selected: false
  expanded: false
  packages:
    - virtualbox
    - virtualbox-host-dkms
    - linux
    - linux-headers
- name: "Virtualbox for Linux-lts kernel"
  description: "Installs virtualbox for linux-lts kernel"
  critical: false
  hidden: false
  selected: false
  expanded: false
  packages:
    - virtualbox
    - virtualbox-host-dkms
    - linux-lts
    - linux-lts-headers
- name: "Vmware"
  description: "Installs vmware software"
  critical: false
  hidden: false
  selected: false
  expanded: false
  packages:
    - open-vm-tools
    - vmware-workstation
    - vmware-keymaps
- name: "Qemu software"
  description: "Installs qemu software"
  critical: false
  hidden: false
  selected: false
  expanded: false
  packages:
    - qemu-base
    - qemu-full
    - quickemu
    - quickemu-git
    - quickgui-bin
